# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='body_html',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
